### ISSUE TITLE
v2

### ISSUE THREAD

**Issue by henkmollema** [henkmollema/Dommel#39]
- [x] Split classes into files
- [x] Support `[Table]` attribute
- [x] Support `[Column]` attribute
- [x] Support `[ForeignKey]` attribute - #72
- [x] Logging of queries
- [x] Fix joining tables (#29, #35)
- [x] Automatic multi-mapping single item
- [x] Add transaction params - #31 
- [x] Paging on Get-queries
- [x] Paging on Select-queries
- [x] Automatic multi-mapping collection
- [x] Multiple primary keys - #54
- [x] Unit tests
- [x] Extend select functionality (e.g. `OrderBy` #56 )
- [ ] ~More advanced SQL builder~ class #84
  - Select all entities
  - Select single entity
  - Insert entity
  - Update entity
  - Delete entity
  - Where-clause
  - and/or-clause 
- [ ] ~Projections~ #85

**Comment by henkmollema** [comment]
#40

**Comment by ivankahl** [comment]
Hi Henk,

Am loving your library.  Definitely proving to be very useful.  Could you tell me when v2 will be released? I am desperately in need of this From functionality.

Also, if there is a roadmap, I can assist with the v2 release.

**Comment by henkmollema** [comment]
@ivankahl the roadmap for 2.0 is pretty much done and there is a beta release available on NuGet (https://www.nuget.org/packages/Dommel/2.0.0-beta4) which is pretty stable. I haven't yet had time to finish up 2.0. There will probably be another, last beta release first.

**Comment by jerone** [comment]
It looks like (almost) all [the work](https://github.com/henkmollema/Dommel/milestone/10) is done. Do you have an ETA when you will finish the new 2.0 release?

**Comment by henkmollema** [comment]
Yeah the work is pretty much done. Just need to find the time to finish it up. I'm hoping to do that in April or May.
